# Copyright 2005-2009 Intel Corporation.  All Rights Reserved.
#
# The source code contained or described herein and all documents related
# to the source code ("Material") are owned by Intel Corporation or its
# suppliers or licensors.  Title to the Material remains with Intel
# Corporation or its suppliers and licensors.  The Material is protected
# by worldwide copyright laws and treaty provisions.  No part of the
# Material may be used, copied, reproduced, modified, published, uploaded,
# posted, transmitted, distributed, or disclosed in any way without
# Intel's prior express written permission.
#
# No license under any patent, copyright, trade secret or other
# intellectual property right is granted to or conferred upon you by
# disclosure or delivery of the Materials, either expressly, by
# implication, inducement, estoppel or otherwise.  Any license under such
# intellectual property rights must be express and approved by Intel in
# writing.

# Per-build Makefile rules (for recursive $(MAKE) calls from Makefile)

# Base compile/link options
MYCXXFLAGS = /nologo $(TBB_SECURITY_SWITCH) /EHsc /Zc:forScope /D WIN32 /D _CRT_SECURE_NO_DEPRECATE $(CXXFLAGS)
MYLFLAGS = /link /incremental:no /fixed:no $(LFLAGS)
CXXFLAGS_NDEBUG = /MD /O2 /Oy /Ot /Gy /D NDEBUG
CXXFLAGS_DEBUG = /MDd /Od /Zi /D _DEBUG

# Specify library directory for Direct X SDK
DDLIB_DIR=$(DXSDK_DIR)\lib\$(XARCH:AMD64=x64)

# Input and output files
#SOURCE = v
#RCNAME = specified externaly
#EXE =    ^
# defaults on XARCH = x86
UISRC = ../../common/gui/$(UI)video.cpp

default:

build_echo:
	-@echo Building$(DEBUG) $(EXE) with UI=$(UI) XARCH=$(XARCH)

build_one:	build_echo build_$(UI)$(DEBUG)

build_con: $(SOURCE) $(UISRC)
	$(CXX) $(CXXFLAGS_NDEBUG) $(MYCXXFLAGS) $(SOURCE) $(UISRC) $(MYLFLAGS) /subsystem:console /OUT:$(EXE)
	@cmd.exe /C del *.obj

build_con_debug: $(SOURCE) $(UISRC)
	$(CXX) $(CXXFLAGS_DEBUG) $(MYCXXFLAGS) $(SOURCE) $(UISRC) $(MYLFLAGS) /debug /subsystem:console /OUT:$(EXE)
	@cmd.exe /C del *.obj

build_gdi: $(SOURCE) $(UISRC) vc7.1/$(RCNAME).res
	$(CXX) $(CXXFLAGS_NDEBUG) /D _WINDOWS $(MYCXXFLAGS) $(SOURCE) $(UISRC) $(MYLFLAGS) vc7.1/$(RCNAME).res /subsystem:windows /machine:$(XARCH) /OUT:$(EXE)
	@cmd.exe /C del *.obj

build_gdi_debug: $(SOURCE) $(UISRC) vc7.1/$(RCNAME).res
	$(CXX) $(CXXFLAGS_DEBUG) /D _WINDOWS $(MYCXXFLAGS) $(SOURCE) $(UISRC) $(MYLFLAGS) vc7.1/$(RCNAME).res /debug /subsystem:windows /machine:$(XARCH) /OUT:$(EXE)
	@cmd.exe /C del *.obj

build_dd: $(SOURCE) $(UISRC) vc7.1/$(RCNAME).res
	-@echo Using DirectX SDK from "$(DDLIB_DIR)"
	$(CXX) $(CXXFLAGS_NDEBUG) /D _WINDOWS $(MYCXXFLAGS) /I "$(DXSDK_DIR)\include" $(SOURCE) $(UISRC) $(MYLFLAGS) /LIBPATH:"$(DDLIB_DIR)" vc7.1/$(RCNAME).res /subsystem:windows /machine:$(XARCH) /OUT:$(EXE)
	@cmd.exe /C del *.obj

build_dd_debug: $(SOURCE) $(UISRC) vc7.1/$(RCNAME).res
	-@echo Using DirectX SDK from "$(DDLIB_DIR)"
	$(CXX) $(CXXFLAGS_DEBUG) /D _WINDOWS $(MYCXXFLAGS) /I "$(DXSDK_DIR)\include" $(SOURCE) $(UISRC) $(MYLFLAGS) /LIBPATH:"$(DDLIB_DIR)" vc7.1/$(RCNAME).res /debug /subsystem:windows /machine:$(XARCH) /OUT:$(EXE)
	@cmd.exe /C del *.obj

vc7.1/$(RCNAME).res:
	rc /r vc7.1/$(RCNAME)
